Config = {
    --SMG--
	["WEAPON_MICROSMG"] = {
        model="w_sb_microsmg", 
        back_bone = 24818,
        x = 0.07,
        y = -0.2,
        z = -0.15,
        x_rotation = -80.0,
        y_rotation = 180.0,
        z_rotation = 8.0,
    },
    ["WEAPON_SMG"] = {
        model="w_sb_smg", 
        back_bone = 24818,
        x = 0.08,
        y = -0.2,
        z = -0.15,
        x_rotation = -80.0,
        y_rotation = 180.0,
        z_rotation = 8.0,
    },
    ["WEAPON_MG"] = {
        model="w_mg_mg", 
        back_bone = 24818,
        x = 0.1,
        y = -0.2,
        z = -0.15,
        x_rotation = 100.0,
        y_rotation = 180.0,
        z_rotation = 0.0,
    },
    ["WEAPON_COMBATMG"] = {
        model="w_mg_combatmg", 
        back_bone = 24818,
        x = 0.1,
        y = -0.15,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 135.0,
        z_rotation = 0.0,
    },
    ["WEAPON_COMBATPDW"] = {
        model="w_sb_pdw", 
        back_bone = 24818,
        x = 65536.0,
        y = 65536.0,
        z = 65536.0,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    ["WEAPON_MACHINEPISTOL"] = {
        model="w_sb_compactsmg", 
        back_bone = 24818,
        x = -0.23,
        y = -0.2,
        z = -0.025,
        x_rotation = 180.0,
        y_rotation = -125.0,
        z_rotation = 8.0,
    },
    ["WEAPON_MINISMG"] = {
        model="w_sb_smg", 
        back_bone = 24818,
        x = 0.0,
        y = -0.2,
        z = -0.15,
        x_rotation = 100.0,
        y_rotation = 180.0,
        z_rotation = 0.0,
    },
    --MELE--
    ["WEAPON_KNIFE"] = {
        model="prop_w_me_knife_01", 
        back_bone = 58271,
        x = -0.05,
        y = 0.125,
        z = -0.085,
        x_rotation = -95.0,
        y_rotation = 15.0,
        z_rotation = -120.0,
    },
    ["WEAPON_NIGHTSTICK"] = {
        model="w_me_nightstick", 
        back_bone = 58271,
        x = -0.1,
        y = 0.2,
        z = -0.1,
        x_rotation = -95.0,
        y_rotation = 15.0,
        z_rotation = -130.0,
    },
    ["WEAPON_HAMMER"] = {
        model="prop_tool_hammer", 
        back_bone = 24818,
        x = 65536.0,
        y = 65536.0,
        z = 65536.0,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    ["WEAPON_BAT"] = {
        model="w_me_bat", 
        back_bone = 24818,
        x = 0.3,
        y = -0.12,
        z = -0.12,
        x_rotation = 10.0,
        y_rotation = 290.0,
        z_rotation = 0.0,
    },
    ["WEAPON_GOLFCLUB"] = {
        model="w_me_gclub", 
        back_bone = 24818,
        x = 65536.0,
        y = 65536.0,
        z = 65536.0,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    ["WEAPON_CROWBAR"] = {
        model="w_me_crowbar", 
        back_bone = 24818,
        x = 65536.0,
        y = 65536.0,
        z = 65536.0,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    ["WEAPON_KNUCKLE"] = {
        model="prop_w_me_dagger", 
        back_bone = 24818,
        x = 65536.0,
        y = 65536.0,
        z = 65536.0,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    ["WEAPON_HATCHET"] = {
        model="w_me_hatchet", 
        back_bone = 24818,
        x = 65536.0,
        y = 65536.0,
        z = 65536.0,
        x_rotation = 0.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    ["WEAPON_MACHETE"] = {
        model="prop_ld_w_me_machette", 
        back_bone = 58271,
        x = -0.1,
        y = 0.125,
        z = -0.1,
        x_rotation = -95.0,
        y_rotation = 15.0,
        z_rotation = -130.0,
    },
    ["WEAPON_WRENCH"] = {
        model="w_me_wrench", 
        back_bone = 24818,
        x = -0.2,
        y = -0.12,
        z = 0.1,
        x_rotation = 10.0,
        y_rotation = 180.0,
        z_rotation = 20.0,
    },
    ["WEAPON_SWITCHBLADE"] = {
        model="w_me_switchblade", 
        back_bone = 58271,
        x = -0.05,
        y = 0.125,
        z = -0.085,
        x_rotation = -95.0,
        y_rotation = 15.0,
        z_rotation = -120.0,
    },
    --PISTOL--
    ["WEAPON_PISTOL50"] = {
        model="w_pi_pistol50", 
        back_bone = 51826,
        x = -0.05,
        y = 0.10,
        z = 0.1,
        x_rotation = -135.0,
        y_rotation = 0.0,
        z_rotation = -8.0,
    },
    ["WEAPON_PISTOL"] = {
        model="w_pi_pistol", 
        back_bone = 51826,
        x = 0.0,
        y = 0.10,
        z = 0.1,
        x_rotation = -135.0,
        y_rotation = 0.0,
        z_rotation = -8.0,
    },
    ["WEAPON_COMBATPISTOL"] = {
        model="w_pi_combatpistol", 
        back_bone = 51826,
        x = -0.05,
        y = 0.10,
        z = 0.1,
        x_rotation = -135.0,
        y_rotation = 0.0,
        z_rotation = -8.0,
    },
    ["WEAPON_VINTAGEPISTOL"] = {
        model="w_pi_vintage_pistol", 
        back_bone = 51826,
        x = -0.01,
        y = -0.10,
        z = 0.07,
        x_rotation = -155.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    ["WEAPON_HEAVYPISTOL"] = {
        model="w_pi_heavypistol", 
        back_bone = 24818,
        x = -0.2,
        y = -0.13,
        z = 0.0,
        x_rotation = -155.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    ["WEAPON_SNSPISTOL"] = {
        model="w_pi_sns_pistol", 
        back_bone = 58271,
        x = -0.2,
        y = -0.13,
        z = 0.0,
        x_rotation = -155.0,
        y_rotation = 0.0,
        z_rotation = 0.0,
    },
    ["WEAPON_FLAREGUN"] = {
        model="w_pi_flaregun", 
        back_bone = 58271,
        x = -0.12,
        y = 0.10,
        z = -0.125,
        x_rotation = -45.0,
        y_rotation = 0.0,
        z_rotation = -8.0,
    },
    ["WEAPON_REVOLVER"] = {
        model="w_pi_revolver", 
        back_bone = 51826,
        x = -0.05,
        y = 0.10,
        z = 0.1,
        x_rotation = -135.0,
        y_rotation = 0.0,
        z_rotation = -8.0,
    },
    ["WEAPON_REVOLVER_MK2"] = {
        model="w_pi_revolvermk2", 
        back_bone = 51826,
        x = -0.05,
        y = 0.10,
        z = 0.1,
        x_rotation = -135.0,
        y_rotation = 0.0,
        z_rotation = -8.0,
    },
    ["WEAPON_APPISTOL"] = {
        model="w_pi_appistol", 
        back_bone = 51826,
        x = -0.05,
        y = 0.10,
        z = 0.1,
        x_rotation = -135.0,
        y_rotation = 0.0,
        z_rotation = -8.0,
    },
    ["WEAPON_PISTOL_MK2"] = {
        model="w_pi_pistolmk2", 
        back_bone = 51826,
        x = -0.05,
        y = 0.10,
        z = 0.1,
        x_rotation = -135.0,
        y_rotation = 0.0,
        z_rotation = -8.0,
    },
    ["WEAPON_STUNGUN"] = {
        model="w_pi_stungun", 
        back_bone = 51826,
        x = -0.05,
        y = 0.10,
        z = 0.1,
        x_rotation = -135.0,
        y_rotation = 0.0,
        z_rotation = -8.0,
    },
    ["WEAPON_SNSPISTOL_MK2"] = {
        model="w_pi_sns_pistolmk2", 
        back_bone = 51826,
        x = 0.0,
        y = 0.1,
        z = 0.075,
        x_rotation = -120.0,
        y_rotation = 0.0,
        z_rotation = -8.0,
    },
    --RIFLE--
    ["WEAPON_ASSAULTRIFLE"] = {
        model="w_ar_assaultrifle", 
        back_bone = 24818,
        x = 0.05,
        y = -0.2,
        z = -0.15,
        x_rotation = -80.0,
        y_rotation = 180.0,
        z_rotation = 8.0,
    },
    ["WEAPON_CARBINERIFLE"] = {
        model="w_ar_carbinerifle", 
        back_bone = 24818,
        x = 0.05,
        y = -0.2,
        z = -0.15,
        x_rotation = -80.0,
        y_rotation = 180.0,
        z_rotation = 8.0,
    },
    ["WEAPON_CARBINERIFLE_MK2"] = {
        model="w_ar_carbineriflemk2", 
        back_bone = 24818,
        x = 0.05,
        y = -0.2,
        z = -0.15,
        x_rotation = -80.0,
        y_rotation = 180.0,
        z_rotation = 8.0,
    },
    ["WEAPON_ADVANCEDRIFLE"] = {
        model="w_ar_advancedrifle", 
        back_bone = 24818,
        x = 0.1,
        y = -0.02,
        z = -0.15,
        x_rotation = 100.0,
        y_rotation = 180.0,
        z_rotation = 0.0,
    },
    ["WEAPON_SPECIALCARBINE"] = {
        model="w_ar_specialcarbine", 
        back_bone = 24818,
        x = 0.1,
        y = -0.02,
        z = -0.15,
        x_rotation = 100.0,
        y_rotation = 180.0,
        z_rotation = 0.0,
    },
    ["WEAPON_BULLPUPRIFLE"] = {
        model="w_ar_bullpuprifle", 
        back_bone = 24818,
        x = 0.1,
        y = -0.02,
        z = -0.15,
        x_rotation = 100.0,
        y_rotation = 180.0,
        z_rotation = 0.0,
    },
    ["WEAPON_COMPACTRIFLE"] = {
        model="w_ar_assaultrifle", 
        back_bone = 24818,
        x = 0.1,
        y = -0.02,
        z = -0.15,
        x_rotation = 100.0,
        y_rotation = 180.0,
        z_rotation = 0.0,
    },
    ["WEAPON_BULLPUPRIFLE_MK2"] = {
        model="w_ar_bullpupriflemk2", 
        back_bone = 24818,
        x = 0.05,
        y = -0.25,
        z = -0.15,
        x_rotation = -80.0,
        y_rotation = 180.0,
        z_rotation = 8.0,
    },
    --SHOOTGUN--
    ["WEAPON_PUMPSHOTGUN"] = {
        model="w_sg_pumpshotgun", 
        back_bone = 24818,
        x = 0.1,
        y = -0.15,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 135.0,
        z_rotation = 0.0,
    },
    ["WEAPON_BULLPUPSHOTGUN"] = {
        model="w_sg_assaultshotgun", 
        back_bone = 24818,
        x = 0.1,
        y = -0.15,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 225.0,
        z_rotation = 0.0,
    },
    ["WEAPON_MUSKET"] = {
        model="w_ar_musket", 
        back_bone = 24818,
        x = 0.1,
        y = -0.15,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 135.0,
        z_rotation = 0.0,
    },
    ["WEAPON_HEAVYSHOTGUN"] = {
        model="w_sg_heavyshotgun", 
        back_bone = 24818,
        x = 0.1,
        y = -0.15,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 225.0,
        z_rotation = 0.0,
    },
    ["WEAPON_PUMPSHOTGUN_MK2"] = {
        model="w_sg_pumpshotgunmk2", 
        back_bone = 24818,
        x = 0.1,
        y = -0.15,
        z = -0.1,
        x_rotation = 0.0,
        y_rotation = 220.0,
        z_rotation = 0.0,
    },
    --SNIPER--
    ["WEAPON_SNIPERRIFLE"] = {
        model="w_sr_sniperrifle", 
        back_bone = 24818,
        x = 0.1,
        y = -0.2,
        z = 0.12,
        x_rotation = 100.0,
        y_rotation = 180.0,
        z_rotation = 0.0,
    },
    ["WEAPON_HEAVYSNIPER"] = {
        model="w_sr_heavysniper", 
        back_bone = 24818,
        x = 0.1,
        y = -0.2,
        z = 0.15,
        x_rotation = -100.0,
        y_rotation = 180.0,
        z_rotation = 8.0,
    },
    ["WEAPON_MARKSMANRIFLE"] = {
        model="w_sr_marksmanrifle", 
        back_bone = 24818,
        x = 0.1,
        y = -0.2,
        z = 0.12,
        x_rotation = 100.0,
        y_rotation = 180.0,
        z_rotation = 0.0,
    },
    ["WEAPON_HEAVYSNIPER_MK2"] = {
        model="w_sr_heavysnipermk2", 
        back_bone = 24818,
        x = 0.13,
        y = -0.2,
        z = 0.15,
        x_rotation = -100.0,
        y_rotation = 180.0,
        z_rotation = 8.0,
    },
    ["WEAPON_FIREWORK"] = {
        model="w_lr_firework", 
        back_bone = 24818,
        x = -0.23,
        y = -0.17,
        z = -0.25,
        x_rotation = -90.0,
        y_rotation = 90.0,
        z_rotation = -60.0,
    },
    ["WEAPON_XXX"] = {
        model="XXX", 
        back_bone = 24818,
        x = 0.1,
        y = -0.2,
        z = 0.12,
        x_rotation = 100.0,
        y_rotation = 180.0,
        z_rotation = 30.0,
    },
    ["WEAPON_XXX"] = {
        model="XXX", 
        back_bone = 24818,
        x = 0.1,
        y = -0.2,
        z = 0.12,
        x_rotation = 100.0,
        y_rotation = 180.0,
        z_rotation = 0.0,
    },
    ["WEAPON_XXX"] = {
        model="XXX", 
        back_bone = 24818,
        x = 0.1,
        y = -0.2,
        z = 0.12,
        x_rotation = 100.0,
        y_rotation = 180.0,
        z_rotation = 0.0,
    },
    ["WEAPON_XXX"] = {
        model="XXX", 
        back_bone = 24818,
        x = 0.1,
        y = -0.2,
        z = 0.12,
        x_rotation = 100.0,
        y_rotation = 180.0,
        z_rotation = 0.0,
    },
    ["WEAPON_XXX"] = {
        model="XXX", 
        back_bone = 24818,
        x = 0.1,
        y = -0.2,
        z = 0.12,
        x_rotation = 100.0,
        y_rotation = 180.0,
        z_rotation = 0.0,
    },
    ["WEAPON_XXX"] = {
        model="XXX", 
        back_bone = 24818,
        x = 0.1,
        y = -0.2,
        z = 0.12,
        x_rotation = 100.0,
        y_rotation = 180.0,
        z_rotation = 0.0,
    },
    ["WEAPON_XXX"] = {
        model="XXX", 
        back_bone = 24818,
        x = 0.1,
        y = -0.2,
        z = 0.12,
        x_rotation = 100.0,
        y_rotation = 180.0,
        z_rotation = 0.0,
    },
}