Config = Config or {}
Config.RepeatTimeout = 2000
Config.CallRepeats = 10
Config.TweetDuration = 3600
Config.UseESXLicense = false
Config.UseESXBilling = true

Config.Garasinya = {
    ['Garkot'] = 'A',
    ['Garasi_Rusun'] = 'B',
    ['Garasi_Perumahan'] = 'C',
    ['Garasi_SandyS'] = 'D',
    ['Garasi_Tobaco'] = 'E',
    ['Paleto_Bay'] = 'F',
    ['Garasi_Walkot'] = 'G',
    ['Garasi_Kanpol'] = 'H',
    ['Garasi_RS'] = 'I',
    ['Garasi_Gym'] = 'J',
    ['Garasi_Pelabuhan'] = 'K'
}

Config.PhoneApplications = {
    ["phone"] = {
        app = "phone",
        color = "#04b543",
        icon = "fa fa-phone-alt",
        tooltipText = "Phone",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 1,
        Alerts = 0,
    },
    ["whatsapp"] = {
        app = "whatsapp",
        color = "#25d366",
        icon = "fas fa-comment",
        tooltipText = "Whatsapp",
        tooltipPos = "top",
        style = "font-size: 2.8vh";
        job = false,
        blockedjobs = {},
        slot = 2,
        Alerts = 0,
    },
    ["settings"] = {
        app = "settings",
        color = "#636e72",
        icon = "fa fa-cogs",
        tooltipText = "Settings",
        tooltipPos = "top",
        style = "padding-right: .08vh; font-size: 2.3vh";
        job = false,
        blockedjobs = {},
        slot = 12,
        Alerts = 0,
    },
    ["twitter"] = {
        app = "twitter",
        color = "#1da1f2",
        icon = "fab fa-twitter",
        tooltipText = "Twitter",
        tooltipPos = "top",
        job = false,
        blockedjobs = {},
        slot = 4,
        Alerts = 0,
    },
    ["garage"] = {
        app = "garage",
        color = "#575fcf",
        icon = "fas fa-car",
        tooltipText = "Garasi",
        job = false,
        blockedjobs = {},
        slot = 5,
        Alerts = 0,
    },
    ["mail"] = {
        app = "mail",
        color = "#ff002f",
        icon = "fas fa-envelope-open-text",
        tooltipText = "Mail",
        job = false,
        blockedjobs = {},
        slot = 6,
        Alerts = 0,
    },
    ["advert"] = {
        app = "advert",
        color = "#ff8f1a",
        icon = "fas fa-bullhorn",
        tooltipText = "Iklan",
        job = false,
        blockedjobs = {},
        slot = 7,
        Alerts = 0,
    },
    ["bank"] = {
        app = "bank",
        color = "#9c88ff",
        icon = "fas fa-money-check-alt",
        tooltipText = "Bank",
        job = false,
        blockedjobs = {},
        slot = 8,
        Alerts = 0,
    },
    ["documents"] = {
        app = "documents",
        color = "#f15ac1",
        icon = "fas fa-sticky-note",
        tooltipText = "Notepad",
        job = false,
        blockedjobs = {},
        slot = 13,
        Alerts = 0,
    },
    ["calculator"] = {
        app = "calculator",
        color = "#004682",
        icon = "fas fa-calculator",
        tooltipText = "Calculator",
        job = false,
        blockedjobs = {},
        slot = 9,
        Alerts = 0,
    },
    ["racing"] = {
        app = "racing",
        color = "#353b48",
        icon = "fas fa-flag-checkered",
        tooltipText = "Balapan",
        job = false,
        blockedjobs = {},
        slot = 10,
        Alerts = 0,
    },
    ["houses"] = {
        app = "houses",
        color = "#27ae60",
        icon = "fas fa-home",
        tooltipText = "Houses",
        job = false,
        blockedjobs = {},
        slot = 11,
        Alerts = 0,
    }, 
    ["meos"] = {
        app = "meos",
        color = "#004682",
        icon = "fas fa-ad",
        tooltipText = "MDT",
        job = "ambulance",
        blockedjobs = {'mechanic', 'police', 'pedagang', 'taxi', 'state'},
        slot = 16,
        Alerts = 0,
    },
    ["lawyers"] = {
        app = "lawyers",
        color = "#26d4ce",
        icon = "fas fa-briefcase",
        tooltipText = "Layanan",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 3,
        Alerts = 0,
    },
    ["gallery"] = {
        app = "gallery",
        color = "#AC1D2C",
        icon = "fas fa-images",
        tooltipText = "Gallery",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 15,
        Alerts = 0,
    },
    ["camera"] = {
        app = "camera",
        color = "#AC1D2C",
        icon = "fas fa-camera",
        tooltipText = "Camera",
        tooltipPos = "bottom",
        job = false,
        blockedjobs = {},
        slot = 14,
        Alerts = 0,
    }	
}