var tableauQuestion = [
    {   question : "APA YANG DI MASKUD DENGAN ROLEPLAY?",
        propositionA : "Bermain Game GTA V Dengan Menggunakan FiveM",
        propositionB : "Bermain Peran",
        propositionC : "Bermain GTA V Online",
        propositionD : "Bermain FiveM",
        reponse : "B"},
    {   question : "APA ITU IC ?",
        propositionA : "IN - GAME CHARACTER(SESUATU YANG BERHUBUNGAN DENGAN KARAKTERMU)",
        propositionB : "IN - COUNTRY(SESUATU YANG BERHUBUNGAN DENGAN KOTA",
        propositionC : "IN - OUTCHARACTER(SESUATU YANG TIDAK BERHUBUNGAN DENGAN KARAKTERMU",
        propositionD : "IN - GAME CENTER(SESUATU YANG BERADA DI TENGAH TENGAH ROLEPLAY)",
        reponse : "A"},
    {   question : "/report DI GUNAKAN KETIKA? ",
        propositionA : "Membutuhkan dana di kota",
        propositionB : "Minta di hidupin saat perang ",
        propositionC : "Untuk meminta Bantuan di saat bug",
        propositionD : "Melaporkan  hal yang tidak penting",
        reponse : "C"},
    {   question : "HAL PENTING APA YANG HARUS DI LAKUKAN PADA SETIAP WARGA?",
        propositionA : "Menghargai sesama player",
        propositionB : "Mengumpulkan uang sebanyak banyaknya",
        propositionC : "Perang setiap saat",
        propositionD : "Merampok untuk mendapatkan uang",
        reponse : "A"},
    {   question : "APA ITU OOC?",
        propositionA : "IN - GAME CHARACTER(SESUATU YANG BERHUBUNGAN DENGAN KARAKTERMU)",
        propositionB : "IN - COUNTRY(SESUATU YANG BERHUBUNGAN DENGAN KOTA",
        propositionC : "OUT OFF CHARCATER(SESUATU YANG TIDAK BERHUBUNGAN DENGAN KARAKTERMU",
        propositionD : "IN - GAME CENTER(SESUATU YANG BERADA DI TENGAH TENGAH ROLEPLAY)",
        reponse : "C"},
    {   question : "APA YANG DI MAKSUD DENGAN MIXING?",
        propositionA : "ALAT UNTUN MENCAMPUR",
        propositionB : "MENCAMPURKAN HAL IC - OOC",
        propositionC : "MENGGUNAKAN BAHASA KOTOR DI IC",
        propositionD : "ALAT UNTUK MICROPHONE",
        reponse : "B"},
    {   question : "KETIKA ANDA MELANGGAR ATURAN SERVER APA YANG AKAN ANDA LAKUKAN ?",
        propositionA : "Menerima hukuman sesuai aturan kota",
        propositionB : "Membuat akun baru untuk masuk kota",
        propositionC : "Membuat rusuh di discord",
        propositionD : "Membawa masalah ini sampai ke OOC ",
        reponse : "A"},
    {   question : "APA ITU VDM ?",
        propositionA : "Rusuh/memukul warga lain",
        propositionB : "Berbicara kasar ke warga lain",
        propositionC : "Menabrak Orang Lain Dengan Sengaja",
        propositionD : "Menembak  Orang Lain Dengan Sengaja",
        reponse : "C"},
    {   question : "Apa bila anda  berada di lokasi perampokan apa yang anda lakukan?",
        propositionA : "Pura pura tidak tau",
        propositionB : "Menjauh dari lokasi perampokan",
        propositionC : "Ikut ngerampok",
        propositionD : "Keliling di lokasi perampokan",
        reponse : "B"},
    {   question : "Apa yang akan kalian lakukan jika melakukan Fail RP?",
        propositionA : "Meminta Maaf dan tidak akan melakukannya lagi",
        propositionB : "Melanjukan tindakan fail yang kalian lakukan",
        propositionC : "Tidak merasa bersalah jika di laporkan oleh warga lain",
        propositionD : "Berbuat onar di Discord",
        reponse : "A"},
]
